// Global list of ~190 countries
export const COUNTRIES = [
  "United States",
  "India",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Brazil",
  "Mexico",
  "Japan",
  "China",
  "South Korea",
  "Singapore",
  "United Arab Emirates",
  "Saudi Arabia",
  "South Africa",
  "Sweden",
  "Switzerland",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Belgium",
  "Austria",
  "Greece",
  "Portugal",
  "Ireland",
  "New Zealand",
  "Thailand",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Pakistan",
  "Bangladesh",
  "Nigeria",
  "Kenya",
  "Egypt",
  "Morocco",
  "Turkey",
  "Israel",
  "Iran",
  "Iraq",
  "UAE",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Jordan",
  "Lebanon",
  "Syria",
  "Palestinian Territory",
  "Yemen",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Venezuela",
  "Ecuador",
  "Bolivia",
  "Paraguay",
  "Uruguay",
  "Costa Rica",
  "Guatemala",
  "Honduras",
  "El Salvador",
  "Nicaragua",
  "Panama",
  "Dominican Republic",
  "Jamaica",
  "Trinidad and Tobago",
  "Bahamas",
  "Barbados",
  "Cuba",
  "Haiti",
  "Puerto Rico",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Serbia",
  "Croatia",
  "Slovenia",
  "Slovakia",
  "Bulgaria",
  "Latvia",
  "Lithuania",
  "Estonia",
  "Ukraine",
  "Belarus",
  "Russia",
  "Kazakhstan",
  "Uzbekistan",
  "Turkmenistan",
  "Tajikistan",
  "Kyrgyzstan",
  "Georgia",
  "Armenia",
  "Azerbaijan",
  "Afghanistan",
  "Nepal",
  "Bhutan",
  "Sri Lanka",
  "Maldives",
  "Cambodia",
  "Laos",
  "Myanmar",
  "Mongolia",
  "Taiwan",
  "Hong Kong",
  "Macau",
  "Papua New Guinea",
  "Fiji",
  "Solomon Islands",
  "Samoa",
  "Vanuatu",
  "Kiribati",
  "Nauru",
  "Tuvalu",
  "Palau",
  "Marshall Islands",
  "Micronesia",
  "Mozambique",
  "Tanzania",
  "Uganda",
  "Rwanda",
  "Burundi",
  "Ethiopia",
  "Somalia",
  "Djibouti",
  "Sudan",
  "South Sudan",
  "Angola",
  "Zambia",
  "Zimbabwe",
  "Malawi",
  "Botswana",
  "Namibia",
  "Lesotho",
  "Eswatini",
  "Madagascar",
  "Mauritius",
  "Seychelles",
  "Comoros",
  "Ghana",
  "Ivory Coast",
  "Senegal",
  "Mali",
  "Burkina Faso",
  "Niger",
  "Guinea",
  "Guinea-Bissau",
  "Gambia",
  "Benin",
  "Togo",
  "Liberia",
  "Sierra Leone",
  "Chad",
  "Central African Republic",
  "Cameroon",
  "Equatorial Guinea",
  "Gabon",
  "Republic of the Congo",
  "Democratic Republic of the Congo",
  "Mauritania",
  "Western Sahara",
  "Libya",
  "Tunisia",
  "Algeria",
  "Sudan",
  "Bonaire, Sint Eustatius and Saba",
  "Curacao",
  "Sint Maarten",
  "Anguilla",
  "Antigua and Barbuda",
  "Aruba",
  "Bermuda",
  "British Virgin Islands",
  "Cayman Islands",
  "Dominica",
  "Grenada",
  "Guadeloupe",
  "Martinique",
  "Montserrat",
  "Saint Barthélemy",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Vincent and the Grenadines",
  "United States Virgin Islands",
  "Turks and Caicos Islands",
  "Belize",
  "Guyana",
  "Suriname",
  "French Guiana",
  "Falkland Islands",
  "South Georgia and the South Sandwich Islands",
  "Greenland",
  "Faroe Islands",
  "Iceland",
  "Albania",
  "Bosnia and Herzegovina",
  "Kosovo",
  "Macedonia",
  "Montenegro",
  "Moldova",
  "Liechtenstein",
  "Luxembourg",
  "Malta",
  "Cyprus",
  "Brunei",
  "East Timor",
  "North Korea",
  "Samoa",
  "Tonga",
  "Solomon Islands",
  "Vanuatu",
  "French Polynesia",
  "New Caledonia",
  "Guam",
  "Northern Mariana Islands",
  "American Samoa",
  "Cook Islands",
  "Niue",
  "Tokelau",
  "Wallis and Futuna"
];

// Event types
export const EVENT_TYPES = [
  { value: "music", label: "Music & Festival" },
  { value: "tech", label: "Tech & Business" },
  { value: "sports", label: "Sports & Outdoor" },
  { value: "fashion", label: "Fashion & Lifestyle" },
  { value: "food", label: "Food & Beverage" },
  { value: "art", label: "Art & Culture" },
  { value: "charity", label: "Charity & Non-Profit" },
  { value: "corporate", label: "Corporate & Conference" }
];

// Creator niches / categories
export const CONTENT_TYPES = [
  "Reels",
  "Posts",
  "Stories",
  "YouTube",
  "TikTok"
];

// Audience size options
export const AUDIENCE_SIZES = [
  "1K-10K",
  "10K-50K",
  "50K-100K",
  "100K+"
];

// Industry options
export const INDUSTRIES = [
  "Fashion",
  "Tech",
  "Fitness",
  "Food",
  "Travel",
  "Gaming",
  "Beauty",
  "Entertainment",
  "Finance",
  "Health & Wellness",
  "Lifestyle",
  "Education",
  "Business",
  "Sports",
  "Automotive",
  "Real Estate",
  "Home & Decor",
  "Music",
  "Art & Design",
  "Other"
];

// Creator niches for primary niche
export const CREATOR_NICHES = [
  "Photography",
  "Video Production",
  "Blogging",
  "UGC",
  "Live Streaming",
  "Reviews",
  "Comedy",
  "Music",
  "Fashion",
  "Fitness",
  "Food",
  "Travel",
  "Gaming",
  "Tech",
  "Beauty",
  "Lifestyle",
  "Other"
];
